### ISSUE TITLE
add a patreon man

### ISSUE THREAD

**Issue by rodrigo1593** [size43-gamemakerserver/statuspage#1]
gamemakerserver end of life is in 2024 (or at least that's how i understood.

then why you don't create a patreon specifically to mantain the server. (and a little for you) it could be great...
and i guess its better to show everyone your last goodbye. because this is part of our chilhood hehe...

also. if you somewhere in your hearth prefer to mantain this alive then expand yourself to godot & game maker studio 2.

and.... make it still free and friendly. but with a patreon :)

**Comment by size43-gamemakerserver** [comment]
There are lots of things I wish I could do, but unfortunately I have very little free time. The reality is that GameMaker Server would never make enough money to justify giving it the love, care and attention it deserves. You can read my thoughts here: https://gamemakerserver.com/nl/news/102/

I want to keep GameMaker Server alive as long as possible, but I also want to set realistic expectations. I don't know what I'll be doing a few years from now, so I can't promise I'll keep it alive forever. Right now I've committed to keeping it alive until at least the end of 2024. Around that time I'll re-evaluate to see if I can keep it alive another year.
